FROM node:24-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

# Copy dependency
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy application source code
COPY . .

# Expose Next.js development server port
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
